### ISSUE TITLE
Action boost model

### ISSUE THREAD

**Issue by LamannaLeonardo** [964728623/robothor_challenge_objnav21#2]
Hi,

congratulations for winning the RoboTHOR object navigation challenge 2021!

I am working on the same task, and I would like to run your method, but I am not able to find the trained model. Could you please upload the trained action boost model that won the challenge?

Thank you,
Leonardo

**Comment by 964728623** [comment]
Hi @LeonardoL96 ,
Thanks for your congratulations. We focused on other methods at that time, but this structure won unexpectedly. So the trained model is not well preserved. You can do less than 10M steps of training based on the official baseline to get it and refer to notes when testing.We are doing in-depth research on this model, so we have no computing resources to reproduce it until September 8, 2021.

Thank you,
Bai

**Comment by LamannaLeonardo** [comment]
Ah ok, thank you for the indications.

Leonardo
